

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        includes    = [bld.Path('Code/CryEngine/CryAction'),
		bld.Path('Gems\Environment_Tile_System_v2\Code\Include\Environment_Tile_System_v2'),
		bld.Path('Gems\DragonCrashCollectibles\Code\Include\DragonCrashCollectibles'),
		bld.Path('Gems\DragonCrashController\Code\Include\DragonCrashController')
		],
    )
